import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import {
  Sparkles,
  Trophy,
  Download,
  RotateCcw,
  LayoutDashboard,
  CheckCircle2,
  AlertTriangle,
  Compass,
  FileCode,
  Share2,
  Zap,
} from 'lucide-react';
import jsPDF from 'jspdf';
import { interviewService } from '../services/api';
import { InterviewSession } from '../types';
import { useAuth } from '../context/AuthContext';
import { XPStoreModal } from '../components/gamification/XPStoreModal';

export const InterviewResultPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const { user, refreshProfile } = useAuth();
  const [interview, setInterview] = useState<InterviewSession | null>(null);
  const [loading, setLoading] = useState(true);
  const [showXpModal, setShowXpModal] = useState(false);

  useEffect(() => {
    refreshProfile().catch(() => {});
  }, []);

  useEffect(() => {
    if (!id) return;
    interviewService.getInterview(id).then((res) => {
      if (res.success && res.interview) {
        setInterview(res.interview);
      }
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [id]);

  const handleDownloadPdf = () => {
    if (!interview) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title & Header
    doc.setFontSize(20);
    doc.setTextColor(30, 58, 138); // Dark Blue
    doc.text('InterviewAI - Performance Report', 14, 22);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Role: ${interview.jobRole} | Company Focus: ${interview.companyName || 'General'}`, 14, 30);
    doc.text(`Completed: ${new Date(interview.completedAt || Date.now()).toLocaleDateString()}`, 14, 36);

    // Overall Score
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 42, pageWidth - 14, 42);

    doc.setFontSize(14);
    doc.setTextColor(20, 20, 20);
    doc.text(`Overall Score: ${interview.overallScore || 80}/100`, 14, 52);

    // Category Scores
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    const cat = interview.categoryScores || {
      technicalKnowledge: 82,
      communication: 80,
      confidence: 78,
      problemSolving: 85,
      hrSkills: 80,
    };
    doc.text(`- Technical Knowledge: ${cat.technicalKnowledge}/100`, 18, 62);
    doc.text(`- Communication: ${cat.communication}/100`, 18, 68);
    doc.text(`- Confidence & Delivery: ${cat.confidence}/100`, 18, 74);
    doc.text(`- Problem Solving: ${cat.problemSolving}/100`, 18, 80);

    // Strengths
    let y = 92;
    doc.setFontSize(12);
    doc.setTextColor(22, 101, 52); // Green
    doc.text('Key Strengths:', 14, y);
    y += 6;

    const strengths = interview.summaryReport?.strengths || ['Good architectural understanding', 'Clear articulation of trade-offs'];
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    strengths.slice(0, 4).forEach((str) => {
      doc.text(`• ${str}`, 18, y);
      y += 6;
    });

    // Weaknesses
    y += 4;
    doc.setFontSize(12);
    doc.setTextColor(180, 83, 9); // Amber
    doc.text('Areas for Improvement:', 14, y);
    y += 6;

    const weaknesses = interview.summaryReport?.weaknesses || ['Provide more concrete production metrics', 'Elaborate on edge cases'];
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    weaknesses.slice(0, 4).forEach((wk) => {
      doc.text(`• ${wk}`, 18, y);
      y += 6;
    });

    // 5-Day Roadmap Preview
    y += 6;
    doc.setFontSize(12);
    doc.setTextColor(30, 58, 138);
    doc.text('Recommended 5-Day Action Plan:', 14, y);
    y += 6;

    const roadmap = interview.summaryReport?.learningRoadmap || [];
    doc.setFontSize(9);
    roadmap.slice(0, 5).forEach((item) => {
      doc.text(`${item.day}: ${item.topic} - ${item.details.substring(0, 80)}`, 18, y);
      y += 6;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by InterviewAI Platform powered by Gemini AI', 14, 285);

    doc.save(`InterviewAI_Report_${interview.id.substring(0, 8)}.pdf`);
  };

  if (loading || !interview) {
    return (
      <div className="min-h-[70vh] flex flex-col items-center justify-center space-y-4">
        <div className="w-12 h-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin" />
        <p className="text-sm font-semibold text-zinc-500 dark:text-zinc-400">
          Compiling your interview telemetry...
        </p>
      </div>
    );
  }

  const score = interview.overallScore || 82;
  const isHire = score >= 80;

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-16">
      {/* Hero Result Banner */}
      <div className="p-8 rounded-3xl bg-gradient-to-r from-blue-900 via-indigo-900 to-zinc-900 text-white shadow-xl relative overflow-hidden">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 relative z-10">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 backdrop-blur-md border border-white/20 text-xs font-semibold mb-3">
              <Trophy className="w-3.5 h-3.5 text-amber-300" />
              <span>Interview Completed</span>
            </div>
            <h1 className="text-3xl font-extrabold tracking-tight">
              Evaluation & Preparation Report
            </h1>
            <p className="mt-1 text-xs text-zinc-300">
              {interview.jobRole} • {interview.companyName || 'Standard Tech Round'} • {interview.interviewType}
            </p>
          </div>

          <div className="flex items-center gap-4">
            <div className="text-center p-4 rounded-2xl bg-white/10 backdrop-blur-md border border-white/20">
              <span className="text-4xl font-black text-white">{score}</span>
              <span className="text-xs text-zinc-300 block font-semibold">Overall / 100</span>
            </div>

            <div className="flex flex-col gap-2">
              <button
                id="download-pdf-btn"
                onClick={handleDownloadPdf}
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white text-zinc-900 hover:bg-zinc-100 font-bold text-xs shadow-md transition-all"
              >
                <Download className="w-4 h-4 text-blue-600" />
                <span>Download PDF</span>
              </button>
              <Link
                to="/interview/setup"
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-md transition-all text-center justify-center"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span>Retake</span>
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Session XP Deduction & Balance Banner */}
      <div className="p-4 sm:p-5 rounded-2xl bg-amber-500/10 border border-amber-500/25 dark:bg-amber-950/20 dark:border-amber-800/40 flex flex-col sm:flex-row items-center justify-between gap-4 shadow-sm">
        <div className="flex items-center gap-3 w-full sm:w-auto">
          <div className="w-10 h-10 rounded-xl bg-amber-500/20 text-amber-600 dark:text-amber-400 flex items-center justify-center shrink-0 font-black">
            <Zap className="w-5 h-5 fill-amber-500 text-amber-500" />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-xs font-bold uppercase tracking-wider text-amber-700 dark:text-amber-300">
                Mock Interview Session Completed
              </span>
              <span className="px-2 py-0.5 rounded-full text-[11px] font-extrabold bg-red-500/15 text-red-600 dark:text-red-400 border border-red-500/20">
                -100 XP Deducted
              </span>
            </div>
            <p className="text-xs text-zinc-600 dark:text-zinc-300 mt-0.5">
              100 XP was deducted for conducting this AI evaluation session. Current Balance:{' '}
              <strong className="text-zinc-900 dark:text-white font-bold">{user?.xpPoints ?? 0} XP</strong> • Level:{' '}
              <span className="font-semibold text-blue-600 dark:text-blue-400">{user?.level || 'Intermediate'}</span>
            </p>
          </div>
        </div>

        <button
          id="recharge-xp-btn-result"
          type="button"
          onClick={() => setShowXpModal(true)}
          className="w-full sm:w-auto whitespace-nowrap px-4 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600 text-white text-xs font-bold shadow-sm transition-all text-center"
        >
          ⚡ Recharge XP (Razorpay)
        </button>
      </div>

      {/* Category Performance Bars */}
      <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-sm space-y-4">
        <h3 className="font-bold text-base text-zinc-900 dark:text-white">
          Category Performance Index
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <div className="flex justify-between text-xs font-semibold mb-1">
              <span className="text-zinc-700 dark:text-zinc-300">Technical Depth</span>
              <span className="text-blue-600 dark:text-blue-400 font-bold">
                {interview.categoryScores?.technicalKnowledge || 85}%
              </span>
            </div>
            <div className="w-full h-2 rounded-full bg-zinc-100 dark:bg-zinc-800 overflow-hidden">
              <div
                className="h-full bg-blue-600 rounded-full"
                style={{ width: `${interview.categoryScores?.technicalKnowledge || 85}%` }}
              />
            </div>
          </div>

          <div>
            <div className="flex justify-between text-xs font-semibold mb-1">
              <span className="text-zinc-700 dark:text-zinc-300">Communication & Articulation</span>
              <span className="text-indigo-600 dark:text-indigo-400 font-bold">
                {interview.categoryScores?.communication || 82}%
              </span>
            </div>
            <div className="w-full h-2 rounded-full bg-zinc-100 dark:bg-zinc-800 overflow-hidden">
              <div
                className="h-full bg-indigo-600 rounded-full"
                style={{ width: `${interview.categoryScores?.communication || 82}%` }}
              />
            </div>
          </div>

          <div>
            <div className="flex justify-between text-xs font-semibold mb-1">
              <span className="text-zinc-700 dark:text-zinc-300">Confidence & Delivery</span>
              <span className="text-violet-600 dark:text-violet-400 font-bold">
                {interview.categoryScores?.confidence || 80}%
              </span>
            </div>
            <div className="w-full h-2 rounded-full bg-zinc-100 dark:bg-zinc-800 overflow-hidden">
              <div
                className="h-full bg-violet-600 rounded-full"
                style={{ width: `${interview.categoryScores?.confidence || 80}%` }}
              />
            </div>
          </div>

          <div>
            <div className="flex justify-between text-xs font-semibold mb-1">
              <span className="text-zinc-700 dark:text-zinc-300">Problem Solving & Trade-offs</span>
              <span className="text-emerald-600 dark:text-emerald-400 font-bold">
                {interview.categoryScores?.problemSolving || 88}%
              </span>
            </div>
            <div className="w-full h-2 rounded-full bg-zinc-100 dark:bg-zinc-800 overflow-hidden">
              <div
                className="h-full bg-emerald-600 rounded-full"
                style={{ width: `${interview.categoryScores?.problemSolving || 88}%` }}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Strengths & Weaknesses Breakdown */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <div className="p-6 rounded-3xl bg-white dark:bg-zinc-900 border border-emerald-200/70 dark:border-emerald-900/40 shadow-sm space-y-3">
          <div className="flex items-center gap-2 text-sm font-bold text-emerald-700 dark:text-emerald-400">
            <CheckCircle2 className="w-4 h-4" />
            <span>Demonstrated Strengths</span>
          </div>
          <ul className="space-y-2 text-xs text-zinc-600 dark:text-zinc-300">
            {(interview.summaryReport?.strengths || ['Good architectural explanation of caching', 'Sound understanding of Spring Boot annotations']).map((s, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-emerald-500 font-bold">•</span>
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="p-6 rounded-3xl bg-white dark:bg-zinc-900 border border-amber-200/70 dark:border-amber-900/40 shadow-sm space-y-3">
          <div className="flex items-center gap-2 text-sm font-bold text-amber-700 dark:text-amber-400">
            <AlertTriangle className="w-4 h-4" />
            <span>Target Improvement Areas</span>
          </div>
          <ul className="space-y-2 text-xs text-zinc-600 dark:text-zinc-300">
            {(interview.summaryReport?.weaknesses || ['Elaborate on production scalability constraints', 'Structure answers with concise bullet points']).map((w, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-amber-500 font-bold">•</span>
                <span>{w}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* 5-Day Personalized Learning Roadmap */}
      {interview.summaryReport?.learningRoadmap && (
        <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-sm space-y-4">
          <div className="flex items-center gap-2">
            <Compass className="w-5 h-5 text-blue-600" />
            <h3 className="font-bold text-base text-zinc-900 dark:text-white">
              Personalized 5-Day Preparation Roadmap
            </h3>
          </div>
          <p className="text-xs text-zinc-500 dark:text-zinc-400">
            Custom-tailored study plan addressing your weaker answers from this session:
          </p>

          <div className="space-y-3">
            {interview.summaryReport.learningRoadmap.map((step, idx) => (
              <div
                key={idx}
                className="p-4 rounded-2xl bg-zinc-50 dark:bg-zinc-800/40 border border-zinc-200/80 dark:border-zinc-700/60"
              >
                <div className="flex items-center justify-between font-bold text-xs text-blue-600 dark:text-blue-400 mb-1">
                  <span>{step.day}</span>
                  <span className="text-zinc-700 dark:text-zinc-300">{step.topic}</span>
                </div>
                <p className="text-xs text-zinc-600 dark:text-zinc-400 leading-relaxed">{step.details}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Return to Dashboard CTA */}
      <div className="flex justify-between items-center pt-4">
        <Link
          to="/dashboard"
          className="flex items-center gap-2 text-xs font-semibold text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white"
        >
          <LayoutDashboard className="w-4 h-4" />
          <span>Return to Dashboard</span>
        </Link>

        <Link
          to="/interview/setup"
          className="flex items-center gap-2 px-6 py-3 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-md shadow-blue-600/20"
        >
          <span>Start Another Practice Round</span>
        </Link>
      </div>

      <XPStoreModal
        isOpen={showXpModal}
        onClose={() => {
          setShowXpModal(false);
          refreshProfile().catch(() => {});
        }}
        currentXp={user?.xpPoints ?? 100}
        currentLevel={user?.level || 'Beginner'}
        onSuccess={(_newXp, _newLevel, updatedUser) => {
          if (updatedUser) {
            refreshProfile().catch(() => {});
          }
        }}
      />
    </div>
  );
};
